Mollie.WebApplicationCoreExample/Controllers/CustomerController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Api.Models.Customer;
using Mollie.WebApplicationCoreExample.Models;
using Mollie.WebApplicationCoreExample.Services.Customer;
using Mollie.WebApplicationCoreExample.Services;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class CustomerController : Controller {
        private readonly ICustomerOverviewClient _customerOverviewClient;
        private readonly ICustomerStorageClient _customerStorageClient;

        public CustomerController(ICustomerOverviewClient customerOverviewClient, ICustomerStorageClient customerStorageClient) {
            this._customerOverviewClient = customerOverviewClient;
            this._customerStorageClient = customerStorageClient;
        }

        [HttpGet]
        public async Task<ViewResult> Index() {
            OverviewModel<CustomerResponse> model = await this._customerOverviewClient.GetList();
            return this.View(model);
        }

        [HttpGet]
        public async Task<ViewResult> ApiUrl([FromQuery]string url) {
            OverviewModel<CustomerResponse> model = await this._customerOverviewClient.GetListByUrl(url);
            return this.View(nameof(this.Index), model);
        }

        [HttpGet]
        public ViewResult Create() {
            CreateCustomerModel model = new CreateCustomerModel();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCustomerModel model) {
            if (!this.ModelState.IsValid) {
                return this.View();
            }

            await this._customerStorageClient.Create(model);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Mollie.WebApplicationCoreExample/Controllers/PaymentController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Api.Models;
using Mollie.Api.Models.Payment.Response;
using Mollie.WebApplicationCoreExample.Models;
using Mollie.WebApplicationCoreExample.Services;
using Mollie.WebApplicationCoreExample.Services.Payment;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class PaymentController : Controller {
        private readonly IPaymentOverviewClient _paymentOverviewClient;
        private readonly IPaymentStorageClient _paymentStorageClient;

        public PaymentController(IPaymentOverviewClient paymentOverviewClient, IPaymentStorageClient paymentStorageClient) {
            this._paymentOverviewClient = paymentOverviewClient;
            this._paymentStorageClient = paymentStorageClient;
        }

        [HttpGet]
        public async Task<ViewResult> Index() {
            OverviewModel<PaymentResponse> model = await this._paymentOverviewClient.GetList();
            return this.View(model);
        }

        [HttpGet]
        public async Task<ViewResult> ApiUrl([FromQuery]string url) {
            OverviewModel<PaymentResponse> model = await this._paymentOverviewClient.GetListByUrl(url);
            return this.View(nameof(this.Index), model);
        }

        [HttpGet]
        public ViewResult Create() {
            CreatePaymentModel model = new CreatePaymentModel() {
                Amount = 10,
                Currency = Currency.EUR
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePaymentModel model) {
            if (!this.ModelState.IsValid) {
                return this.View();
            }

            await this._paymentStorageClient.Create(model);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Mollie.WebApplicationCoreExample/Controllers/PaymentMethodController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Api.Models.PaymentMethod;
using Mollie.WebApplicationCoreExample.Models;
using Mollie.WebApplicationCoreExample.Services.PaymentMethod;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class PaymentMethodController : Controller {
        private readonly IPaymentMethodOverviewClient _paymentMethodOverviewClient;

        public PaymentMethodController(IPaymentMethodOverviewClient paymentMethodOverviewClient) {
            this._paymentMethodOverviewClient = paymentMethodOverviewClient;
        }

        public async Task<ViewResult> Index() {
            OverviewModel<PaymentMethodResponse> model = await this._paymentMethodOverviewClient.GetList();
            return this.View(model);
        }
    }
}

Mollie.WebApplicationCoreExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Mollie API Demo Application - @ViewBag.Title</title>

    <link rel="stylesheet" href="~/css/bundles/vendor.min.css">
    <environment include="Development">
        <link href="~/css/Site.css" rel="stylesheet" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bundles/site.min.css">
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">Mollie API Demo Application</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Payment">Payments</a></li>
                <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="PaymentMethod">Payment methods</a></li>
                <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Customer">Customers</a></li>
            </ul>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script type="text/javascript" src="~/js/bundles/vendor.min.js"></script>
    <environment include="Development">
    </environment>

    <environment exclude="Development">
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Mollie.WebApplicationCoreExample/Views/Shared/_OverviewNavigation.cshtml
@model OverviewNavigationLinksModel 

<div class="clearfix">
    @if (Model.Previous != null) {
        <a class="btn btn-primary" role="button" asp-action="ApiUrl" asp-route-url="@Model.Previous.Href">&lt;&lt; Previous</a>
    }

    @if (Model.Next != null) {
        <a class="btn btn-primary float-right" role="button" asp-action="ApiUrl" asp-route-url="@Model.Next.Href">Next &gt;&gt;</a>
    }
</div>