Mollie.WebApplicationCoreExample/Controllers/CustomerController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Api.Models.Customer;
using Mollie.WebApplicationCoreExample.Models;
using Mollie.WebApplicationCoreExample.Services.Customer;
using Mollie.WebApplicationCoreExample.Services;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class CustomerController : Controller {
        private readonly ICustomerOverviewClient _customerOverviewClient;
        private readonly ICustomerStorageClient _customerStorageClient;

        public CustomerController(ICustomerOverviewClient customerOverviewClient, ICustomerStorageClient customerStorageClient) {
            this._customerOverviewClient = customerOverviewClient;
            this._customerStorageClient = customerStorageClient;
        }

        [HttpGet]
        public async Task<ViewResult> Index() {
            OverviewModel<CustomerResponse> model = await this._customerOverviewClient.GetList();
            return this.View(model);
        }

        [HttpGet]
        public async Task<ViewResult> ApiUrl([FromQuery]string url) {
            OverviewModel<CustomerResponse> model = await this._customerOverviewClient.GetListByUrl(url);
            return this.View(nameof(this.Index), model);
        }

        [HttpGet]
        public ViewResult Create() {
            CreateCustomerModel model = new CreateCustomerModel();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCustomerModel model) {
            if (!this.ModelState.IsValid) {
                return this.View();
            }

            await this._customerStorageClient.Create(model);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Mollie.WebApplicationCoreExample/Controllers/MandateController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Api.Models.Mandate;
using Mollie.WebApplicationCoreExample.Models;
using Mollie.WebApplicationCoreExample.Services.Mandate;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class MandateController : Controller {
        private readonly IMandateOverviewClient _mandateOverviewClient;
        private readonly IMandateStorageClient _mandateStorageClient;

        public MandateController(IMandateOverviewClient mandateOverviewClient, IMandateStorageClient mandateStorageClient) {
            this._mandateOverviewClient = mandateOverviewClient;
            this._mandateStorageClient = mandateStorageClient;
        }

        public async Task<ViewResult> Index(string customerId) {
            this.ViewBag.CustomerId = customerId;
            OverviewModel<MandateResponse> model = await this._mandateOverviewClient.GetList(customerId);
            return this.View(model);
        }

        [HttpGet]
        public async Task<ViewResult> ApiUrl([FromQuery]string url) {
            OverviewModel<MandateResponse> model = await this._mandateOverviewClient.GetListByUrl(url);
            return this.View(nameof(this.Index), model);
        }

        [HttpGet]
        public ViewResult Create(string customerId) {
            this.ViewBag.CustomerId = customerId;
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(string customerId) {
            await this._mandateStorageClient.Create(customerId);
            return this.RedirectToAction("Index", new { customerId });
        }
    }
}

Mollie.WebApplicationCoreExample/Controllers/SubscriptionController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Api.Models;
using Mollie.Api.Models.Subscription;
using Mollie.WebApplicationCoreExample.Models;
using Mollie.WebApplicationCoreExample.Services.Subscription;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class SubscriptionController : Controller {
        private readonly ISubscriptionOverviewClient _subscriptionOverviewClient;
        private readonly ISubscriptionStorageClient _subscriptionStorageClient;

        public SubscriptionController(ISubscriptionOverviewClient subscriptionOverviewClient, ISubscriptionStorageClient subscriptionStorageClient) {
            this._subscriptionOverviewClient = subscriptionOverviewClient;
            this._subscriptionStorageClient = subscriptionStorageClient;
        }

        [HttpGet]
        public async Task<ViewResult> Index(string customerId) {
            this.ViewBag.CustomerId = customerId;
            OverviewModel<SubscriptionResponse> model = await this._subscriptionOverviewClient.GetList(customerId);
            return this.View(model);
        }

        [HttpGet]
        public async Task<ViewResult> ApiUrl([FromQuery]string url) {
            OverviewModel<SubscriptionResponse> model = await this._subscriptionOverviewClient.GetListByUrl(url);
            return this.View(nameof(this.Index), model);
        }

        [HttpGet]
        public ViewResult Create(string customerId) {
            CreateSubscriptionModel model = new CreateSubscriptionModel() {
                CustomerId = customerId,
                Amount = 10,
                Currency = Currency.EUR
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSubscriptionModel model) {
            if (!this.ModelState.IsValid) {
                return this.View();
            }

            await this._subscriptionStorageClient.Create(model);
            return this.RedirectToAction(nameof(this.Index), new { customerId = model.CustomerId });
        }
    }
}

Mollie.WebApplicationCoreExample/Views/Customer/Create.cshtml
@model CreateCustomerModel

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <h2>Create new customer</h2>

    <form method="post">
        <div asp-validation-summary="All"></div>

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" />
                </div>

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input class="form-control" asp-for="Email" />
                </div>

                <input type="submit" name="Save" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

Mollie.WebApplicationCoreExample/Views/Customer/Index.cshtml
@model OverviewModel<CustomerResponse>

@{
    ViewData["Title"] = "List payments";
}

<div class="container">
    <h2>List of customers</h2>

    <div class="clearfix">
        <a asp-action="Create" class="btn btn-primary float-right">Create new customer</a>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Date created</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Locale</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (CustomerResponse customer in Model.Items) {
                <tr>
                    <td>@customer.Id</td>
                    <td>@customer.CreatedAt</td>
                    <td>@customer.Name</td>
                    <td><a href="mailto:@customer.Email">@customer.Email</a></td>
                    <td>@customer.Locale</td>
                    <td>
                        <a asp-controller="Mandate" asp-action="Index" asp-route-customerId="@customer.Id" class="btn btn-outline-secondary">View mandates</a>
                        <a asp-controller="Subscription" asp-action="Index" asp-route-customerId="@customer.Id" class="btn btn-outline-secondary">View subscriptions</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <partial name="_OverviewNavigation" model="Model.Navigation" />
</div>