Mollie.WebApplicationCoreExample/Controllers/PaymentController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Api.Models;
using Mollie.Api.Models.Payment.Response;
using Mollie.WebApplicationCoreExample.Models;
using Mollie.WebApplicationCoreExample.Services;
using Mollie.WebApplicationCoreExample.Services.Payment;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class PaymentController : Controller {
        private readonly IPaymentOverviewClient _paymentOverviewClient;
        private readonly IPaymentStorageClient _paymentStorageClient;

        public PaymentController(IPaymentOverviewClient paymentOverviewClient, IPaymentStorageClient paymentStorageClient) {
            this._paymentOverviewClient = paymentOverviewClient;
            this._paymentStorageClient = paymentStorageClient;
        }

        [HttpGet]
        public async Task<ViewResult> Index() {
            OverviewModel<PaymentResponse> model = await this._paymentOverviewClient.GetList();
            return this.View(model);
        }

        [HttpGet]
        public async Task<ViewResult> ApiUrl([FromQuery]string url) {
            OverviewModel<PaymentResponse> model = await this._paymentOverviewClient.GetListByUrl(url);
            return this.View(nameof(this.Index), model);
        }

        [HttpGet]
        public ViewResult Create() {
            CreatePaymentModel model = new CreatePaymentModel() {
                Amount = 10,
                Currency = Currency.EUR
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePaymentModel model) {
            if (!this.ModelState.IsValid) {
                return this.View();
            }

            await this._paymentStorageClient.Create(model);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Mollie.WebApplicationCoreExample/Controllers/RefundController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.WebApplicationCoreExample.Services.Payment.Refund;

namespace Mollie.WebApplicationCoreExample.Controllers {
    public class RefundController : Controller {
        private readonly IRefundPaymentClient _refundPaymentClient;

        public RefundController(IRefundPaymentClient refundPaymentClient) {
            this._refundPaymentClient = refundPaymentClient;
        }

        [HttpPost]
        public async Task<IActionResult> Refund(string paymentId) {
            await this._refundPaymentClient.Refund(paymentId);
            return this.RedirectToAction(nameof(PaymentController.Index), "Payment");
        }
    }
}

Mollie.WebApplicationCoreExample/Views/Payment/Create.cshtml
@model CreatePaymentModel

@{
    ViewData["Title"] = "Create payment";
}

<div class="container">
    <h2>Create new payment</h2>

    <form method="post">
        <div asp-validation-summary="All"></div>
        
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="Amount"></label>
                    <input class="form-control" asp-for="Amount" autocomplete="off" />
                </div>

                <div class="form-group">
                    <label asp-for="Currency"></label>
                    <select class="form-control" asp-for="Currency" asp-items="@Html.GetStaticStringSelectList(typeof(Currency))"></select>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea class="form-control" asp-for="Description" rows="4"></textarea>
                </div>

                <input type="submit" name="Save" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

Mollie.WebApplicationCoreExample/Views/Payment/Index.cshtml
@model OverviewModel<PaymentResponse>

@{
    ViewData["Title"] = "List payments";
}

<div class="container">
    <h2>List of payments</h2>
    
    <div class="clearfix">
        <a asp-action="Create" class="btn btn-primary float-right">Create new payment</a>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Date created</th>
                <th scope="col">Amount</th>
                <th scope="col">Status</th>
                <th scope="col">Method</th>
                <th scope="col">Metadata</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (PaymentResponse payment in Model.Items) {
                <tr>
                    <td>@payment.Id</td>
                    <td>@payment.CreatedAt</td>
                    <td>@payment.Amount.ToString()</td>
                    <td>@payment.Status</td>
                    <td>@payment.Method</td>
                    <td>
                        @if (!String.IsNullOrEmpty(payment.Metadata)) {
                            <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" data-target="#metadata-payment-@payment.Id" aria-expanded="false" aria-controls="collapseExample">
                                Show metadata
                            </button>

                            <div class="collapse" id="metadata-payment-@payment.Id">
                                <div class="card card-body">
                                    @payment.Metadata
                                </div>
                            </div>
                        }
                    </td>
                    <td>
                        @if (payment.Status == PaymentStatus.Open) {
                            <a href="@payment.Links.Checkout.Href" class="btn btn-outline-secondary" target="_blank">Pay</a>
                        }
                        
                        @if (payment.Status == PaymentStatus.Paid) {
                            <form method="post" asp-controller="Refund" asp-action="Refund" asp-route-paymentId="@payment.Id">
                                <input type="submit" name="Refund" value="Refund" class="btn btn-outline-secondary"/>
                            </form>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
    <partial name="_OverviewNavigation" model="Model.Navigation" />
</div>